// Export — turn a completed analysis into shareable Markdown. Ported from the
// markdown half of exporter.js (HTML export is out of scope for v1).

export function toMarkdown(d: any): string {
  if (!d) return "";
  const out: string[] = [];
  const push = (...l: string[]) => out.push(...l);

  push(`# ${d.repoId || "Repository"}`, "");
  if (d.description) push(`> ${d.description}`, "");
  const meta = [d.language, d.license, d.stars ? `${d.stars}★` : null, d.platform].filter(
    (x) => x && x !== "Unknown",
  );
  if (meta.length) push(meta.join(" · "), "");
  if (d.health && d.health.score != null)
    push(`**Health:** ${d.health.score}/100${d.health.summary ? ` — ${d.health.summary}` : ""}`, "");

  const para = (title: string, body?: string) => {
    if (body) push(`## ${title}`, "", body, "");
  };
  const kvList = (title: string, obj?: Record<string, string>) => {
    if (obj && Object.values(obj).some(Boolean)) {
      push(`## ${title}`, "");
      for (const [k, v] of Object.entries(obj)) if (v) push(`- **${k.replace(/_/g, " ")}:** ${v}`);
      push("");
    }
  };

  para("ELI5", d.eli5);
  para("Technical", d.technical);
  kvList("Use Cases", d.use_cases);
  kvList("Skip If", d.skip_if);
  para("Enables", d.enables);

  if (d.pros?.length || d.cons?.length) {
    push("## Pros & Cons", "");
    if (d.pros?.length) {
      push("**Pros**");
      d.pros.forEach((p: string) => push(`- ${p}`));
      push("");
    }
    if (d.cons?.length) {
      push("**Cons**");
      d.cons.forEach((c: string) => push(`- ${c}`));
      push("");
    }
  }
  if (d.alternatives?.length) {
    push("## Alternatives", "");
    d.alternatives.forEach((a: any) => push(`- **${a.name}** — ${a.when}`));
    push("");
  }
  if (d.tech_stack?.built_with?.length || d.tech_stack?.key_dependencies?.length) {
    push("## Tech Stack", "");
    if (d.tech_stack.built_with?.length) push(`Built with: ${d.tech_stack.built_with.join(", ")}`, "");
    if (d.tech_stack.key_dependencies?.length) {
      push("**Key dependencies**");
      d.tech_stack.key_dependencies.forEach((k: any) => push(`- \`${k.name}\` — ${k.purpose}`));
      push("");
    }
  }
  if (d.red_flags?.length) {
    push("## Red Flags", "");
    d.red_flags.forEach((f: any) => push(`- ${f.severity === "ok" ? "✅" : "⚠️"} **${f.title}** — ${f.text}`));
    push("");
  }
  if (d.start_here?.length) {
    push("## Start Here", "");
    d.start_here.forEach((e: any) => push(`- ${e.icon || ""} **${e.title}** (${e.tag}) — ${e.desc}`));
    push("");
  }

  push("---", "_Generated by RepoLens._");
  return out.join("\n");
}

export function slugify(s: string): string {
  return (
    String(s || "repo")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "repo"
  );
}
