import { describe, it, expect } from "vitest";
import { toMarkdown, slugify } from "./export";

describe("export", () => {
  it("emits markdown with title + sections", () => {
    const md = toMarkdown({
      repoId: "a/b",
      eli5: "hello",
      pros: ["p1"],
      cons: ["c1"],
      health: { score: 80 },
    });
    expect(md).toContain("# a/b");
    expect(md).toContain("## ELI5");
    expect(md).toContain("- p1");
    expect(md).toContain("_Generated by RepoLens._");
  });
  it("slugify", () => {
    expect(slugify("Facebook/React!")).toBe("facebook-react");
  });
});
